[package]
name = "hello_hwp_com"
version = "0.1.0"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
hwp_com = { version = "0.1.0", path = "../hwp_com" }

[dependencies.windows]
version = "0.62"
features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_UI_WindowsAndMessaging", # MessageBox와 PostQuitMessage를 위해 필수
    "Win32_System_Variant",
]
